---
kind: pipeline
type: kubernetes
name: build

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: registry.k3s-cluster.benfleming.nz/_/benfleming.nz
    cache_from: registry.k3s-cluster.benfleming.nz/_/benfleming.nz:latest
    tags: latest