---
kind: pipeline
type: kubernetes
name: build

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: registry.k3s-cluster.benfleming.nz
    repo: benfleming.nz
    cache_from: benfleming.nz:latest
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
