---
kind: pipeline
type: kubernetes
name: build

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: index.benfleming.nz
    repo: index.benfleming.nz/benfleming.nz
    cache_from: index.benfleming.nz/benfleming.nz:latest
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
