name: Build & Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone code from repo
      uses: actions/checkout@v1
      
    - name: install nodejs v10
      uses: actions/setup-node@v1
  
    - name: install graphicmagick
      run: |
        sudo apt-get update
        sudo apt-get install graphicsmagick
      
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
        
    - name: deploy dist folder to s3
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_REGION: 'eu-central-1'
        FILE: ./dist
