name: Build & Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone code from repo
      uses: actions/checkout@v1
      
    - name: install nodejs v10
      uses: actions/setup-node@v1
  
    - name: install graphicmagick
      run: |
        apt-get update
        apt-get install graphicsmagick
      
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
        
    - name: deploy dist folder to s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'
