name: Deploy on different branch

on: 
  push:
    branches:    
      - master    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: clone code from repo
        uses: actions/checkout@v1

      - name: install nodejs v10
        uses: actions/setup-node@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: npm install, build
        run: |
          npm ci
          npm run generate --if-present
          ls -la

      - name: push static site to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
